/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.coreyshupe.tempfix1192;

import com.google.inject.Inject;
import com.velocitypowered.api.event.Subscribe;
import com.velocitypowered.api.event.proxy.ProxyInitializeEvent;
import com.velocitypowered.api.plugin.Plugin;
import com.velocitypowered.api.proxy.ProxyServer;

@Plugin(
    id = "temp_fix",
    description = "Temp fix for 1.19.2 client crap.",
    authors = {
        "Corey Shupe (FiXed)"
    },
    name = "TempFix",
    url = "https://github.com/CoreyShupe/TempMC1.19.2Fix",
    version = "0.0.1"
)
public class App {
    private final ProxyServer server;

    @Inject
    public App(ProxyServer server) {
        this.server = server;
    }

    @Subscribe
    public void onInitialize(ProxyInitializeEvent ignored) {
        this.server.getEventManager().register(this, new Listener());
    }
}
